# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f78bd7c2c3620180abc08d2ea0e66d8cfd3d2647ae095b0e7190c2481b1e6966fab3187b82380df30c8ee9f10b921c880941be724456015d838d15ebca2485a0

test:
  secret_key_base: 94561fb74baf2ad5d97bb2e6381b76acdfcc4af75207478a87a806dc3338836468b1826be4f260df73a95b761b0d01b2c086243337c674f032b777b3412a0a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
